'use strict';

export const ACTION_POSTS_GET = 'ACTION_POSTS_GET';
export const ACTION_POSTS_GET_SUCCESS = 'ACTION_POSTS_GET_SUCCESS';
export const ACTION_POSTS_GET_ERROR = 'ACTION_POSTS_GET_ERROR';

export const ACTION_SINGLE_POST_GET = 'ACTION_SINGLE_POST_GET';
export const ACTION_SINGLE_POST_GET_SUCCESS = 'ACTION_SINGLE_POST_GET_SUCCESS';
export const ACTION_SINGLE_POST_GET_ERROR = 'ACTION_SINGLE_POST_GET_ERROR';

export const POSTS_ERROR_MESSAGE = 'Sorry, there was an error loading the news. Please try again.';

export const SINGLE_POST_UPDATED = 'SINGLE_POST_UPDATED';
export const SINGLE_POST_GET_SUCCESS = 'SINGLE_POST_GET_SUCCESS';
export const SINGLE_POST_GET_ERROR = 'SINGLE_POST_GET_ERROR';
export const SINGLE_POST_GET_COMPLETE = 'SINGLE_POST_GET_COMPLETE';
export const SINGLE_POST_GET_ERROR_MESSAGE = 'Sorry, there was an error loading the comments. Please try again.';
export const SINGLE_POST_CLICK = 'SINGLE_POST_CLICK';
